export const FORM_GET_ACCOUNTS = "FORM_GET_ACCOUNTS";
export const GET_USER_TOKEN = "GET_USER_TOKEN";
export const GET_USER_EMAIL = "GET_USER_EMAIL";
export const GET_USER_NAME = "GET_USER_NAME";
// export const CLEAR_PERSIST = "CLEAR_PERSIST";
